/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Write a program to toggle the On Board LED with some delay
 * Case 1 : Use push pull configuration for the output pin
 * Case 2 : Use the Open drain configuration for the output pin
 */
#include <stdint.h>
#include <stdio.h>

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"

// #if !defined(__SOFT_FP__) && defined(__ARM_FP)
//   #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
// #endif
void delay(void)
{
  for (uint32_t i = 0; i < 500000; ++i)
    ;
}

// void Gpio_Config(GPIO_Handle_t Gpio,GPIO_RegDef_t * pGPIOx )

int main(void)
{ // salman
  GPIO_Handle_t GpioLed_1;
  GpioLed_1.pGPIOx = GPIOD;
  GpioLed_1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
  GpioLed_1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GpioLed_1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
  GpioLed_1.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
  GpioLed_1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

  GPIO_Handle_t GpioLed_2;
  GpioLed_2.pGPIOx = GPIOD;
  GpioLed_2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
  GpioLed_2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GpioLed_2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
  GpioLed_2.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
  GpioLed_2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

  GPIO_Handle_t GpioLed_3;
  GpioLed_3.pGPIOx = GPIOD;
  GpioLed_3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
  GpioLed_3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GpioLed_3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
  GpioLed_3.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
  GpioLed_3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

  GPIO_Handle_t GpioLed_4;
  GpioLed_4.pGPIOx = GPIOD;
  GpioLed_4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
  GpioLed_4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
  GpioLed_4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
  GpioLed_4.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
  GpioLed_4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

  GPIO_Handle_t GpioBtn;
  GpioBtn.pGPIOx = GPIOA;
  GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
  GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
  GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
  GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

  GPIO_PeriClockControl(GPIOD, ENABLE);
  GPIO_PeriClockControl(GPIOA, ENABLE);

  GPIO_Init(&GpioLed_1);
  GPIO_Init(&GpioLed_2);
  GPIO_Init(&GpioLed_3);
  GPIO_Init(&GpioLed_4);
  GPIO_Init(&GpioBtn);
  while (1)
  {

    // if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0))
    // {
    //   	GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
    //   	GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_13);
    //   	GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_14);
    //   	GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_15);
    // }
    GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
    delay();
    GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
    delay();
    GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
    delay();
    GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
    delay();
  }
  return 0;
}
