/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Write a program to toggle the On Board LED with some delay
 * Case 1 : Use push pull configuration for the output pin
 * Case 2 : Use the Open drain configuration for the output pin
 */
#include <stdint.h>
#include <stdio.h>


#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_spi_driver.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
void delay(void)
{
	for(uint32_t i =0;i<500000;++i);
}

//void Gpio_Config(GPIO_Handle_t Gpio,GPIO_RegDef_t * pGPIOx )


//This function is used to initialize the gpio pins to behave as SPI2 pins
void SPI2_GPIOInits()
{

    /*
     * SPI 2 Pin Config
     * PB14  --> MISO
     * PB15 --> MOSi
     * PB13  --> SCLK
     * PB12  --> NSS
     * ALT fun mode : 5
     */
	GPIO_Handle_t SPI2_Pins;

	SPI2_Pins.pGPIOx = GPIOB;
	SPI2_Pins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	SPI2_Pins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SPI2_Pins.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPE_PP;
	SPI2_Pins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPI2_Pins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	//SCLK'
	SPI2_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SPI2_Pins);

	//MOSI
	SPI2_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&SPI2_Pins);

	//MISO
	SPI2_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_Init(&SPI2_Pins);

	//NSS
	SPI2_Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&SPI2_Pins);
}

void SPI2_Inits()
{
	SPI_Handle_t SPI2handle;

	SPI2handle.pSPIx = SPI2;
	SPI2handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI2handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI2handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;
	SPI2handle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SPI2handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI2handle.SPIConfig.SPI_SSM = SPI_SSM_EN;

	SPI_Init(&SPI2handle);

}

int main(void)
{
   char userData[] = "HelloWorld!";
   SPI2_GPIOInits();
   SPI2_Inits();

   /* This makes NSS signal internally  high and avoid MODF error */
   SPI_SSIConfig(SPI2, ENABLE);

   //Enable SPI2 Peripheral
   SPI_PeripheralControl(SPI2, ENABLE);
   SPI_SendData(SPI2,(uint8_t*)userData, sizeof(userData));
   SPI_PeripheralControl(SPI2, DISABLE);
   while(1)
    {

    }
    return 0;
}
